branch-defaults:
  master:
    environment: InternshipSystem-env
environment-defaults:
  InternshipSystem-env:
    branch: null
    repository: null
global:
  application_name: internship-system
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Node.js running on
    64bit Amazon Linux/4.5.0
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
