version: 2

jobs:
  build:
    docker:
      - image: "node:carbon"
    steps:
      - run:
          name: Check env
          command: node --version && npm --version
      - checkout
      - restore_cache:
          key: survey-server-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: survey-server-{{ checksum "package.json" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - .

  deploy:
    docker:
      - image: "coxauto/aws-ebcli"
    steps:
      - attach_workspace:
          at: .
      - run:
          name: check eb cli
          command: eb --version
      - run:
          name: Deploy to AWS Beanstalk
          command: eb deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - build